Repository BedrockStreaming/prescaling-exporter, pull requests merged in 2022-08, with the labels that each got.

#34 fix: rename module to match github url
  cmd/clean.go
  cmd/serv.go
  generated/client/clientset/versioned/clientset.go
  generated/client/clientset/versioned/fake/clientset_generated.go
  generated/client/clientset/versioned/fake/register.go
  generated/client/clientset/versioned/scheme/register.go
  generated/client/clientset/versioned/typed/prescaling.bedrock.tech/v1/fake/fake_prescaling.bedrock.tech_client.go
  generated/client/clientset/versioned/typed/prescaling.bedrock.tech/v1/fake/fake_prescalingevent.go
  generated/client/clientset/versioned/typed/prescaling.bedrock.tech/v1/prescaling.bedrock.tech_client.go
  generated/client/clientset/versioned/typed/prescaling.bedrock.tech/v1/prescalingevent.go
  go.mod
  main.go
  pkg/exporter/exporter.go
  pkg/handlers/event_handlers.go
  pkg/prescaling/desired_scaling.go
  pkg/prescaling/get_hpa.go
  pkg/prescaling/get_hpa_test.go
  pkg/prescaling/prescaling.go
  pkg/server/server.go
  pkg/services/prescaling_event.go
  pkg/services/prescaling_event_test.go
  pkg/utils/utils_test.go
Labels: bug, go

#32 feat(golang): add metrics annotation min_replica values
  .github/workflows/go-test.yml
  pkg/exporter/exporter.go
Labels: enhancement, bump:minor, go

#33 chore: add a regression test covering the timezone issue from v0.2.2
  pkg/services/prescaling_event_test.go
Labels: bug, go

#14 docs: update readme
  README.md
Labels: documentation

#35 chore: update the codegen stuff
  Makefile
  generate_type.sh
  generated/client/clientset/versioned/clientset.go
  generated/client/clientset/versioned/fake/clientset_generated.go
  generated/client/clientset/versioned/fake/register.go
  generated/client/clientset/versioned/scheme/register.go
  generated/client/clientset/versioned/typed/prescaling.bedrock.tech/v1/fake/fake_prescalingevent.go
  generated/client/clientset/versioned/typed/prescaling.bedrock.tech/v1/prescaling.bedrock.tech_client.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/tools.go
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/apis/prescaling.bedrock.tech/v1/types.go
  pkg/exporter/exporter.go
Labels: bump:patch

#38 fix(helm): correct helm relabeling
  .github/workflows/helm-test.yml
  helm/prescaling-exporter/templates/monitor.yaml
  helm/test-values.yml
Labels: bug, bump:patch, helm

#39 refacto: rename metrics
  README.md
  pkg/exporter/exporter.go
Labels: documentation, bump:minor, go

#41 docs(swagger): add code 204 for delete
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  swagger/doc.yaml
Labels: documentation, bump:patch

#42 feat(golang): add metric multiplier
  pkg/exporter/exporter.go
Labels: enhancement, bump:minor, go
